apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cache-deployer-role.yaml
  - cache-deployer-rolebinding.yaml
  - cache-deployer-deployment.yaml
commonLabels:
  app: cache-deployer
images:
  - name: quay.io/katonic/cache-deployer
    newTag: 1.5.0
